import type {
  BuildingTemplate,
  GameContent,
  SpellTemplate,
  TaskTemplate,
  UnitLevelStats,
  UnitTemplate,
} from '../../shared/src/game'

const interpolateLevels = (
  hp1: number,
  hp6: number,
  attack1: number,
  attack6: number,
  armor: number,
  attackIntervalTicks: number,
  moveIntervalTicks: number,
): UnitLevelStats[] =>
  Array.from({ length: 6 }, (_, index) => {
    const ratio = index / 5

    return {
      hp: Math.round(hp1 + (hp6 - hp1) * ratio),
      attack: Math.round(attack1 + (attack6 - attack1) * ratio),
      armor,
      attackIntervalTicks,
      moveIntervalTicks,
    }
  })

const heroes: UnitTemplate[] = [
  {
    id: 'behemoth',
    name: '巨兽',
    kind: 'hero',
    attackType: 'hero',
    armorType: 'hero',
    range: 1,
    footprint: { width: 2, height: 2 },
    population: 0,
    trait: '前排控制，近战高生存。',
    levels: [
      {
        hp: 580,
        attack: 12,
        armor: 3,
        attackIntervalTicks: 8,
        moveIntervalTicks: 5,
      },
    ],
  },
  {
    id: 'succubus',
    name: '魅魔',
    kind: 'hero',
    attackType: 'hero',
    armorType: 'hero',
    range: 7,
    footprint: { width: 2, height: 2 },
    population: 0,
    trait: '远程爆发，适合压低后排血线。',
    levels: [
      {
        hp: 260,
        attack: 9,
        armor: 1,
        attackIntervalTicks: 7,
        moveIntervalTicks: 5,
      },
    ],
  },
  {
    id: 'berserker',
    name: '狂战士',
    kind: 'hero',
    attackType: 'hero',
    armorType: 'hero',
    range: 2,
    footprint: { width: 2, height: 2 },
    population: 0,
    trait: '中前排推进，输出和机动更均衡。',
    levels: [
      {
        hp: 480,
        attack: 14,
        armor: 2,
        attackIntervalTicks: 7,
        moveIntervalTicks: 4,
      },
    ],
  },
]

const units: UnitTemplate[] = [
  {
    id: 'footman',
    name: '步兵',
    kind: 'unit',
    attackType: 'normal',
    armorType: 'light',
    range: 1,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '基础近战。',
    recruitment: { gold: 80, crystal: 0 },
    levels: interpolateLevels(290, 435, 14, 22, 3, 8, 5),
  },
  {
    id: 'troll',
    name: '巨魔',
    kind: 'unit',
    attackType: 'piercing',
    armorType: 'cloth',
    range: 2,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '短距离穿刺。',
    recruitment: { gold: 90, crystal: 20 },
    levels: interpolateLevels(220, 330, 16, 24, 1, 8, 5),
  },
  {
    id: 'archer',
    name: '弓箭手',
    kind: 'unit',
    attackType: 'piercing',
    armorType: 'cloth',
    range: 5,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '基础远程。',
    recruitment: { gold: 200, crystal: 50 },
    levels: interpolateLevels(190, 285, 10, 20, 1, 8, 5),
  },
  {
    id: 'ninja',
    name: '忍者',
    kind: 'unit',
    attackType: 'normal',
    armorType: 'light',
    range: 4,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '中程刺杀。',
    recruitment: { gold: 300, crystal: 60 },
    levels: interpolateLevels(210, 315, 8, 16, 1, 7, 4),
  },
  {
    id: 'priest',
    name: '牧师',
    kind: 'unit',
    attackType: 'heal',
    armorType: 'cloth',
    range: 3,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '优先治疗残血友军。',
    recruitment: { gold: 100, crystal: 150 },
    levels: interpolateLevels(180, 270, 15, 20, 1, 9, 5),
  },
  {
    id: 'mage',
    name: '法师',
    kind: 'unit',
    attackType: 'magic',
    armorType: 'cloth',
    range: 4,
    footprint: { width: 1, height: 1 },
    population: 2,
    trait: '高额魔法伤害。',
    recruitment: { gold: 400, crystal: 300 },
    levels: interpolateLevels(300, 450, 15, 23, 2, 8, 5),
  },
  {
    id: 'knight',
    name: '骑士',
    kind: 'unit',
    attackType: 'normal',
    armorType: 'heavy',
    range: 1,
    footprint: { width: 2, height: 1 },
    population: 3,
    trait: '高护甲重骑。',
    recruitment: { gold: 700, crystal: 120 },
    levels: interpolateLevels(520, 750, 25, 34, 4, 8, 5),
  },
  {
    id: 'wolf_rider',
    name: '狼骑兵',
    kind: 'unit',
    attackType: 'normal',
    armorType: 'cloth',
    range: 5,
    footprint: { width: 2, height: 1 },
    population: 3,
    trait: '大体型远程骑兵。',
    recruitment: { gold: 500, crystal: 300 },
    levels: interpolateLevels(420, 630, 21, 29, 1, 8, 4),
  },
  {
    id: 'shaman',
    name: '萨满',
    kind: 'unit',
    attackType: 'heal',
    armorType: 'cloth',
    range: 2,
    footprint: { width: 1, height: 1 },
    population: 1,
    trait: '用治疗近似早期辅助节奏。',
    recruitment: { gold: 120, crystal: 250 },
    levels: interpolateLevels(240, 300, 20, 33, 1, 9, 5),
  },
  {
    id: 'archangel',
    name: '大天使',
    kind: 'unit',
    attackType: 'magic',
    armorType: 'light',
    range: 5,
    footprint: { width: 2, height: 2 },
    population: 5,
    trait: '高人口高压制的后期法术单位。',
    recruitment: { gold: 600, crystal: 1000 },
    levels: interpolateLevels(700, 980, 25, 34, 2, 8, 5),
  },
  {
    id: 'iron_wheel',
    name: '钢铁之轮',
    kind: 'unit',
    attackType: 'piercing',
    armorType: 'light',
    range: 6,
    footprint: { width: 2, height: 2 },
    population: 4,
    trait: '远程重火力，先用单目标实现。',
    recruitment: { gold: 800, crystal: 600 },
    levels: interpolateLevels(520, 910, 40, 57, 2, 8, 5),
  },
  {
    id: 'troll_cyborg',
    name: '机械巨魔',
    kind: 'unit',
    attackType: 'piercing',
    armorType: 'heavy',
    range: 1,
    footprint: { width: 2, height: 2 },
    population: 8,
    trait: '高人口重装前排。',
    recruitment: { gold: 2000, crystal: 700 },
    levels: interpolateLevels(1700, 2125, 40, 58, 5, 9, 6),
  },
]

const spells: SpellTemplate[] = [
  {
    id: 'shattering_strike',
    name: '破碎打击',
    category: 'targetable',
    baseValue: 10,
    cooldownSeconds: 13,
  },
  {
    id: 'fire_blast',
    name: '烈焰冲击',
    category: 'directional',
    baseValue: 12,
    cooldownSeconds: 15,
  },
  {
    id: 'holy_light',
    name: '圣光',
    category: 'healing',
    baseValue: 100,
    cooldownSeconds: 15,
  },
]

const buildings: BuildingTemplate[] = [
  {
    id: 'castle',
    name: '城堡',
    category: 'default',
    size: { width: 9, height: 9 },
    upgrade: { maxLevel: 5, baseGold: 900, baseCrystal: 240, baseDurationMinutes: 4 },
    economy: { populationBonus: 10 },
  },
  {
    id: 'house',
    name: '住宅',
    category: 'economy',
    size: { width: 3, height: 3 },
    upgrade: { maxLevel: 5, baseGold: 500, baseCrystal: 200, baseDurationMinutes: 3 },
    economy: { populationBonus: 10 },
  },
  {
    id: 'gold_mine',
    name: '金矿',
    category: 'economy',
    size: { width: 5, height: 5 },
    upgrade: { maxLevel: 5, baseGold: 700, baseCrystal: 260, baseDurationMinutes: 3 },
    economy: { resourceId: 'gold', ratePerHour: 330, capacity: 1500 },
  },
  {
    id: 'crystal_mine',
    name: '水晶矿',
    category: 'economy',
    size: { width: 5, height: 5 },
    upgrade: { maxLevel: 5, baseGold: 760, baseCrystal: 280, baseDurationMinutes: 3 },
    economy: { resourceId: 'crystal', ratePerHour: 66, capacity: 400 },
  },
  {
    id: 'warehouse',
    name: '仓库',
    category: 'economy',
    size: { width: 5, height: 5 },
    upgrade: { maxLevel: 5, baseGold: 640, baseCrystal: 220, baseDurationMinutes: 2 },
  },
  {
    id: 'barracks',
    name: '兵营',
    category: 'military',
    size: { width: 5, height: 5 },
    upgrade: { maxLevel: 5, baseGold: 800, baseCrystal: 260, baseDurationMinutes: 3 },
  },
  {
    id: 'shooting_range',
    name: '射击场',
    category: 'military',
    size: { width: 5, height: 5 },
    upgrade: { maxLevel: 5, baseGold: 900, baseCrystal: 320, baseDurationMinutes: 3 },
  },
]

const tasks: TaskTemplate[] = [
  {
    id: 'recruit-starter-squad',
    name: '招募预备队',
    description: '累计招募 3 个基础单位，补齐开荒库存。',
    category: 'recruit',
    eventId: 'recruit_unit',
    scope: 'lifetime',
    goal: 3,
    rewards: { gold: 180, crystal: 30, xp: 40 },
  },
  {
    id: 'collect-economy-cycle',
    name: '城市收成',
    description: '累计收取 4 次资源，完成最小经济循环。',
    category: 'resource',
    eventId: 'collect_resource',
    scope: 'lifetime',
    goal: 4,
    rewards: { gold: 220, crystal: 45, xp: 35 },
  },
  {
    id: 'pve-secure-frontier',
    name: '冒险推进',
    description: '累计赢下 2 场教学战，解锁更多阵容空间。',
    category: 'pve',
    eventId: 'win_pve',
    scope: 'lifetime',
    goal: 2,
    rewards: { gold: 260, crystal: 60, xp: 70 },
  },
  {
    id: 'daily-harvest',
    name: '每日收菜',
    description: '今日完成 2 次资源收取。',
    category: 'daily',
    eventId: 'collect_resource',
    scope: 'daily',
    goal: 2,
    rewards: { gold: 100, crystal: 20, xp: 20 },
  },
  {
    id: 'daily-recruit',
    name: '每日征兵',
    description: '今日完成 1 次招募。',
    category: 'daily',
    eventId: 'recruit_unit',
    scope: 'daily',
    goal: 1,
    rewards: { gold: 120, crystal: 25, xp: 20 },
  },
  {
    id: 'daily-pve',
    name: '每日出征',
    description: '今日赢下 1 场教学战。',
    category: 'daily',
    eventId: 'win_pve',
    scope: 'daily',
    goal: 1,
    rewards: { gold: 140, crystal: 30, xp: 25 },
  },
]

export const gameContent: GameContent = {
  battlefield: {
    rows: 6,
    columns: 15,
    sideADeployEnd: 6,
    sideBDeployStart: 8,
  },
  units: [...heroes, ...units],
  buildings,
  spells,
  tasks,
  tutorialLevels: [
    {
      id: 'tutorial-1',
      name: '教学 1: 城门前哨',
      description: '敌方由步兵和弓箭手组成，适合验证前排顶住后排输出。',
      rewards: { gold: 180, crystal: 30 },
      defender: {
        placements: [
          { unitId: 'behemoth', row: 2, col: 12, level: 1 },
          { unitId: 'footman', row: 1, col: 10, level: 2 },
          { unitId: 'footman', row: 4, col: 10, level: 2 },
          { unitId: 'archer', row: 1, col: 13, level: 2 },
          { unitId: 'archer', row: 4, col: 13, level: 2 },
          { unitId: 'priest', row: 3, col: 11, level: 1 },
        ],
      },
    },
    {
      id: 'tutorial-2',
      name: '教学 2: 侧翼突袭',
      description: '加入忍者和巨魔，要求前排稳住后用中程单位处理侧翼。',
      rewards: { gold: 260, crystal: 45 },
      defender: {
        placements: [
          { unitId: 'berserker', row: 2, col: 12, level: 1 },
          { unitId: 'footman', row: 1, col: 10, level: 2 },
          { unitId: 'footman', row: 4, col: 10, level: 2 },
          { unitId: 'troll', row: 0, col: 13, level: 2 },
          { unitId: 'troll', row: 5, col: 13, level: 2 },
          { unitId: 'ninja', row: 2, col: 14, level: 2 },
        ],
      },
    },
    {
      id: 'tutorial-3',
      name: '教学 3: 重骑压阵',
      description: '敌方出现骑士与法师，开始测试护甲克制和魔法输出。',
      rewards: { gold: 360, crystal: 70 },
      defender: {
        placements: [
          { unitId: 'succubus', row: 2, col: 12, level: 1 },
          { unitId: 'knight', row: 1, col: 10, level: 2 },
          { unitId: 'knight', row: 4, col: 10, level: 2 },
          { unitId: 'mage', row: 1, col: 13, level: 2 },
          { unitId: 'mage', row: 4, col: 13, level: 2 },
          { unitId: 'priest', row: 3, col: 11, level: 2 },
        ],
      },
    },
    {
      id: 'tutorial-4',
      name: '教学 4: 风暴祭坛',
      description: '后期高人口单位进入战场，胜利后可解锁更强初始库存。',
      rewards: { gold: 520, crystal: 120 },
      defender: {
        placements: [
          { unitId: 'behemoth', row: 2, col: 12, level: 1 },
          { unitId: 'iron_wheel', row: 0, col: 10, level: 1 },
          { unitId: 'troll_cyborg', row: 3, col: 10, level: 1 },
          { unitId: 'archer', row: 1, col: 14, level: 3 },
          { unitId: 'archer', row: 4, col: 14, level: 3 },
        ],
      },
    },
  ],
}

export const unitById = Object.fromEntries(gameContent.units.map((unit) => [unit.id, unit]))
export const spellById = Object.fromEntries(gameContent.spells.map((spell) => [spell.id, spell]))
export const buildingById = Object.fromEntries(gameContent.buildings.map((building) => [building.id, building]))
